spring.application.name=api-service
spring.datasource.url=jdbc:postgresql://localhost:5432/notifications
spring.datasource.username=admin
spring.datasource.password=admin
spring.data.redis.host=localhost
spring.data.redis.port=6379