apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-ingress
spec:
  rules:
    - host: short.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: