#!/usr/bin/env python3
"""Generate V5 reseed migration from path list and catalog."""

import re
from collections import Counter
from pathlib import Path
from typing import Dict, List, Tuple

from problem_catalog import ALIASES, CATALOG, SEED_MARKER, SKIP_CLASSES, TOPIC_COLORS

ROOT = Path(__file__).resolve().parents[1]
PATHS_FILE = Path(__file__).resolve().parent / "problem_paths.txt"
OUTPUT_FILE = ROOT / "src/main/resources/db/migration/V5__reseed_study_problems.sql"


def norm_key(class_name: str) -> str:
    key = re.sub(r"[^a-z0-9]", "", class_name.lower())
    return ALIASES.get(key, key)


def class_name_from_path(path: str) -> str:
    return Path(path).name.replace(".java", "")


def is_skipped_class(class_name: str) -> bool:
    if class_name in SKIP_CLASSES:
        return True
    return re.fullmatch(r"Exam(?:\d+)?", class_name) is not None


def sql_escape(value: str) -> str:
    return value.replace("'", "''")


def read_paths() -> List[str]:
    return [line.strip() for line in PATHS_FILE.read_text(encoding="utf-8").splitlines() if line.strip()]


def collect_entries(paths: List[str]):
    selected: Dict[str, Tuple[str, str, str, List[str], str]] = {}
    missing_catalog: List[Tuple[str, str]] = []

    for path in paths:
        class_name = class_name_from_path(path)
        if is_skipped_class(class_name):
            continue

        key = norm_key(class_name)
        if key in selected:
            continue

        data = CATALOG.get(key)
        if data is None:
            missing_catalog.append((class_name, key))
            continue

        selected[key] = data

    return selected, missing_catalog


def build_sql(entries: Dict[str, Tuple[str, str, str, List[str], str]]) -> str:
    markers_where = (
        "description LIKE 'Study problem from personal notes%' "
        "OR description LIKE 'Imported from personal study notes.%'"
    )

    used_topics = sorted({topic for _, topic, _, _, _ in entries.values()})
    used_tags = sorted({tag for _, _, _, tags, _ in entries.values() for tag in tags})

    lines: List[str] = [
        "-- Auto-generated by scripts/generate_problem_seed.py",
        "-- Re-seed study problems from personal notes",
        "",
        "BEGIN;",
        "",
        "-- 1) Delete old V4/V5 personal-note seed data",
        f"DELETE FROM reviews WHERE problem_id IN (SELECT id FROM problems WHERE {markers_where});",
        f"DELETE FROM problem_tags WHERE problem_id IN (SELECT id FROM problems WHERE {markers_where});",
        f"DELETE FROM solutions WHERE problem_id IN (SELECT id FROM problems WHERE {markers_where});",
        f"DELETE FROM problems WHERE {markers_where};",
        "",
        "-- 2) Delete orphaned rows",
        "DELETE FROM reviews r WHERE NOT EXISTS (SELECT 1 FROM problems p WHERE p.id = r.problem_id);",
        "DELETE FROM problem_tags pt WHERE NOT EXISTS (SELECT 1 FROM problems p WHERE p.id = pt.problem_id);",
        "DELETE FROM problem_tags pt WHERE NOT EXISTS (SELECT 1 FROM tags t WHERE t.id = pt.tag_id);",
        "DELETE FROM solutions s WHERE NOT EXISTS (SELECT 1 FROM problems p WHERE p.id = s.problem_id);",
        "",
        "-- 3) Delete unused tags and empty topics, including excluded legacy buckets",
        "DELETE FROM tags t WHERE NOT EXISTS (SELECT 1 FROM problem_tags pt WHERE pt.tag_id = t.id);",
        "DELETE FROM topics t",
        "WHERE t.name IN ('Practice Exams', 'Daily Practice', 'Miscellaneous', 'Design')",
        "  AND NOT EXISTS (SELECT 1 FROM problems p WHERE p.topic_id = t.id);",
        "DELETE FROM topics t",
        "WHERE NOT EXISTS (SELECT 1 FROM problems p WHERE p.topic_id = t.id);",
        "",
        "-- 4) Insert topics, tags, problems, empty solutions, and problem_tags",
    ]

    for topic in used_topics:
        color = TOPIC_COLORS[topic]
        topic_desc = f"Curated {topic.lower()} practice problems from personal notes."
        lines.extend(
            [
                "INSERT INTO topics (name, description, color, created_at, updated_at)",
                f"VALUES ('{sql_escape(topic)}', '{sql_escape(topic_desc)}', '{color}', NOW(), NOW())",
                "ON CONFLICT (name) DO UPDATE",
                "SET description = EXCLUDED.description,",
                "    color = EXCLUDED.color,",
                "    updated_at = NOW();",
                "",
            ]
        )

    for tag in used_tags:
        lines.extend(
            [
                "INSERT INTO tags (name, created_at)",
                f"VALUES ('{sql_escape(tag)}', NOW())",
                "ON CONFLICT (name) DO NOTHING;",
                "",
            ]
        )

    ordered = sorted(entries.items(), key=lambda item: item[1][0].lower())
    for key, (title, topic, difficulty, tags, description) in ordered:
        full_description = f"{SEED_MARKER} {description}"
        lines.extend(
            [
                "INSERT INTO problems (title, url, difficulty, description, favorite, archived, topic_id, created_at, updated_at)",
                "SELECT",
                f"  '{sql_escape(title)}',",
                "  NULL,",
                f"  '{difficulty}',",
                f"  '{sql_escape(full_description)}',",
                "  FALSE,",
                "  FALSE,",
                "  t.id,",
                "  NOW(),",
                "  NOW()",
                "FROM topics t",
                f"WHERE t.name = '{sql_escape(topic)}'",
                f"  AND NOT EXISTS (SELECT 1 FROM problems p WHERE LOWER(p.title) = LOWER('{sql_escape(title)}'));",
                "",
                "INSERT INTO solutions (problem_id, language, source_code, explanation, complexity, mistakes)",
                "SELECT p.id, 'java', '', NULL, NULL, NULL",
                "FROM problems p",
                f"WHERE p.title = '{sql_escape(title)}'",
                "  AND p.description LIKE 'Imported from personal study notes.%';",
                "",
            ]
        )

        for tag in tags:
            lines.extend(
                [
                    "INSERT INTO problem_tags (problem_id, tag_id)",
                    "SELECT p.id, tg.id",
                    "FROM problems p",
                    "JOIN tags tg ON tg.name = '{tag_name}'".format(tag_name=sql_escape(tag)),
                    f"WHERE p.title = '{sql_escape(title)}'",
                    "  AND p.description LIKE 'Imported from personal study notes.%';",
                    "",
                ]
            )

    lines.extend(["COMMIT;", ""])
    return "\n".join(lines)


def main() -> None:
    paths = read_paths()
    entries, missing_catalog = collect_entries(paths)

    if missing_catalog:
        formatted = ", ".join([f"{cls}->{key}" for cls, key in missing_catalog[:10]])
        raise SystemExit(f"Missing catalog entries ({len(missing_catalog)}): {formatted}")

    sql_text = build_sql(entries)
    OUTPUT_FILE.write_text(sql_text, encoding="utf-8")

    topic_distribution = Counter(topic for _, topic, _, _, _ in entries.values())
    print(f"Unique problem count: {len(entries)}")
    print("Topic distribution:")
    for topic, count in sorted(topic_distribution.items()):
        print(f"  {topic}: {count}")
    print(f"Output file: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
