"""Problem catalog generated from personal Java study list."""

SEED_MARKER = "Imported from personal study notes."

SKIP_CLASSES = {"ListNode", "TreeNode", "Node", "LRUCache"}

ALLOWED_TOPICS = [
    "Arrays & Strings",
    "Hash Map / Set",
    "Sliding Window",
    "Prefix Sum",
    "Two Pointers",
    "Binary Search",
    "Linked List",
    "Trees",
    "Graphs",
    "Backtracking",
    "Sorting",
    "Stack",
    "Greedy",
]

TOPIC_COLORS = {
    "Arrays & Strings": "#3b82f6",
    "Hash Map / Set": "#8b5cf6",
    "Sliding Window": "#06b6d4",
    "Prefix Sum": "#14b8a6",
    "Two Pointers": "#f59e0b",
    "Binary Search": "#6366f1",
    "Linked List": "#ec4899",
    "Trees": "#22c55e",
    "Graphs": "#ef4444",
    "Backtracking": "#a855f7",
    "Sorting": "#64748b",
    "Stack": "#f97316",
    "Greedy": "#eab308",
}

ALIASES = {
    "3sum": "threesum",
    "asfarfromlandaspossible": "asfarfromlandaspossible",
    "besttimetobuyandsellstocks": "besttimetobuyandsellstock",
    "combinationssumiii": "combinationsumiii",
    "constructbinarytreefrominorderandpostordertraversal": "constructbinarytreefrominorderandpostordertraversal",
    "constructbinarytreefrompreorderandinordertraversal": "constructbinarytreefrompreorderandinordertraversal",
    "contiguossubarray": "contiguousarray",
    "contiguousarrray": "contiguousarray",
    "continuossubarraysumofatleas2": "continuoussubarraysum",
    "continuoussubarraysumofatleas2": "continuoussubarraysum",
    "deleteduplicatesii": "removeduplicatesfromsortedlistii",
    "firstmissingpossitive": "firstmissingpositive",
    "fruitintobaskets": "fruitintobaskets",
    "fruitsintobaskets": "fruitintobaskets",
    "guessnumberhigherornumber": "guessnumberhigherorlower",
    "intersectionoftwolinkedlist": "intersectionoftwolinkedlists",
    "kokolovestoeatbananas": "kokoeatingbananas",
    "longestsubstringwithoutrepeatingchars": "longestsubstringwithoutrepeatingcharacters",
    "lowestcommonancestorofaabinarytree": "lowestcommonancestorofabinarytree",
    "lowestcommonancestorofbinarytree": "lowestcommonancestorofabinarytree",
    "maximumaveragesubarray": "maximumaveragesubarrayi",
    "maximumaveragesubarrayi": "maximumaveragesubarrayi",
    "maximumdepthofabinarytree": "maximumdepthofbinarytree",
    "maximumdepthofbinarytree": "maximumdepthofbinarytree",
    "maximumsubarrayofsizek": "maximumsumsubarrayofsizek",
    "maximumsumsubarray": "maximumsubarray",
    "maximumsumsubarrayofsizek": "maximumsumsubarrayofsizek",
    "mergetwosortedarrays": "mergesortedarray",
    "mergetwosortedlist": "mergetwosortedlists",
    "minimumwindowsubstring": "minimumwindowsubstring",
    "minimumwindowsubtring": "minimumwindowsubstring",
    "nonioverlappingintervals": "nonoverlappingintervals",
    "pathsumll": "pathsumii",
    "peakindexinamountainarray": "peakindexinamountainarray",
    "prefixsum1": "rangesumqueryimmutable",
    "productarrayexceptself": "productofarrayexceptself",
    "productofarrayexceptself": "productofarrayexceptself",
    "removeduplicatesfromlinkedlist": "removeduplicatesfromsortedlist",
    "removeduplicatesii": "removeduplicatesfromsortedlistii",
    "removelinkedlistelement": "removelinkedlistelements",
    "removenthnodefromtheend": "removenthnodefromendoflist",
    "removethenthnodefromendoflist": "removenthnodefromendoflist",
    "rottingorages": "rottingoranges",
    "searchinrotatedarray": "searchinrotatedsortedarray",
    "searchinsortedarrayii": "searchinrotatedsortedarrayii",
    "sortedsquare": "squaresofasortedarray",
    "squaresofsortedarray": "squaresofasortedarray",
    "substringconcatenationofallwords": "substringwithconcatenationofallwords",
    "substringwithconcatenationofallwords": "substringwithconcatenationofallwords",
    "threesum": "threesum",
    "topkfrequent": "topkfrequentelements",
    "trappingrainingwater": "trappingrainwater",
    "traprainingwater": "trappingrainwater",
    "traprainwater": "trappingrainwater",
    "twosumsorted": "twosumii",
}

# norm_key -> (title, topic, difficulty, tags_list, description)
CATALOG = {
    "allpathsfromsourcetotarget": ("All Paths From Source To Target", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice all paths from source to target using core graphs patterns."),
    "arraypartition": ("Array Partition", "Greedy", "EASY", ["Greedy", "Array"], "Practice array partition using core greedy patterns."),
    "asfarfromlandaspossible": ("As Far from Land as Possible", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice as far from land as possible using core graphs patterns."),
    "balancedbinarytree": ("Balanced Binary Tree", "Trees", "EASY", ["Tree", "DFS"], "Practice balanced binary tree using core trees patterns."),
    "beautifularrangement": ("Beautiful Arrangement", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice beautiful arrangement using core backtracking patterns."),
    "besttimetobuyandsellstock": ("Best Time to Buy and Sell Stock", "Arrays & Strings", "MEDIUM", ["Array", "String"], "Practice best time to buy and sell stock using core arrays & strings patterns."),
    "binarysearch": ("Binary Search", "Binary Search", "EASY", ["Binary Search", "Array"], "Practice binary search using core binary search patterns."),
    "binarysubarrayswithsum": ("Binary Subarrays With Sum", "Prefix Sum", "MEDIUM", ["Prefix Sum", "Hash Map"], "Practice binary subarrays with sum using core prefix sum patterns."),
    "binarytreeinordertraversal": ("Binary Tree Inorder Traversal", "Trees", "EASY", ["Tree", "DFS"], "Practice binary tree inorder traversal using core trees patterns."),
    "binarytreelevelordertraversal": ("Binary Tree Level Order Traversal", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice binary tree level order traversal using core trees patterns."),
    "binarytreelevelordertraversalii": ("Binary Tree Level Order Traversal II", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice binary tree level order traversal ii using core trees patterns."),
    "binarytreemaximumpathsum": ("Binary Tree Maximum Path Sum", "Trees", "HARD", ["Tree", "DFS"], "Practice binary tree maximum path sum using core trees patterns."),
    "binarytreepostordertraversal": ("Binary Tree Postorder Traversal", "Trees", "EASY", ["Tree", "DFS"], "Practice binary tree postorder traversal using core trees patterns."),
    "binarytreepreordertraversal": ("Binary Tree Preorder Traversal", "Trees", "EASY", ["Tree", "DFS"], "Practice binary tree preorder traversal using core trees patterns."),
    "binarytreerightsideview": ("Binary Tree Right Side View", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice binary tree right side view using core trees patterns."),
    "binarytreezigzaglevelordertraversal": ("Binary Tree Zigzag Level Order Traversal", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice binary tree zigzag level order traversal using core trees patterns."),
    "boatstosavepeople": ("Boats To Save People", "Two Pointers", "MEDIUM", ["Two Pointers", "Array"], "Practice boats to save people using core two pointers patterns."),
    "busroutes": ("Bus Routes", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice bus routes using core graphs patterns."),
    "candy": ("Candy", "Greedy", "HARD", ["Greedy", "Array"], "Practice candy using core greedy patterns."),
    "capacitytoshippackageswithinddays": ("Capacity To Ship Packages Within D Days", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice capacity to ship packages within d days using core binary search patterns."),
    "carfleet": ("Car Fleet", "Sorting", "MEDIUM", ["Sorting", "Array"], "Practice car fleet using core sorting patterns."),
    "climbingtheleaderboard": ("Climbingthe Leaderboard", "Greedy", "MEDIUM", ["Greedy", "Array"], "Practice climbingthe leaderboard using core greedy patterns."),
    "clonegraph": ("Clone Graph", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice clone graph using core graphs patterns."),
    "combinations": ("Combinations", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice combinations using core backtracking patterns."),
    "combinationsum": ("Combination Sum", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice combination sum using core backtracking patterns."),
    "combinationsumii": ("Combination Sum II", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice combination sum ii using core backtracking patterns."),
    "combinationsumiii": ("Combination Sum III", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice combination sum iii using core backtracking patterns."),
    "constructbinarytreefrominorderandpostordertraversal": ("Construct Binary Tree from Inorder and Postorder Traversal", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice construct binary tree from inorder and postorder traversal using core trees patterns."),
    "constructbinarytreefrompreorderandinordertraversal": ("Construct Binary Tree from Preorder and Inorder Traversal", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice construct binary tree from preorder and inorder traversal using core trees patterns."),
    "containerwithmostwater": ("Container With Most Water", "Two Pointers", "MEDIUM", ["Two Pointers", "Array"], "Practice container with most water using core two pointers patterns."),
    "containsduplicate": ("Contains Duplicate", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice contains duplicate using core hash map / set patterns."),
    "contiguousarray": ("Contiguous Array", "Prefix Sum", "MEDIUM", ["Prefix Sum", "Hash Map"], "Practice contiguous array using core prefix sum patterns."),
    "continuoussubarraysum": ("Continuous Subarray Sum", "Prefix Sum", "MEDIUM", ["Prefix Sum", "Hash Map"], "Practice continuous subarray sum using core prefix sum patterns."),
    "convertbinarynumberinlinkedlisttointeger": ("Convert Binary Number In Linked List To Integer", "Linked List", "EASY", ["Linked List"], "Practice convert binary number in linked list to integer using core linked list patterns."),
    "countcompletetreenodes": ("Count Complete Tree Nodes", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice count complete tree nodes using core trees patterns."),
    "countnumberofnicesubarrays": ("Count Number Of Nice Sub Arrays", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice count number of nice sub arrays using core sliding window patterns."),
    "countofrangesum": ("Count Of Range Sum", "Prefix Sum", "HARD", ["Prefix Sum", "Hash Map"], "Practice count of range sum using core prefix sum patterns."),
    "dailytemperatures": ("Daily Temperatures", "Stack", "MEDIUM", ["Stack"], "Practice daily temperatures using core stack patterns."),
    "defusethebomb": ("Defuse The Bomb", "Sliding Window", "EASY", ["Sliding Window", "Array"], "Practice defuse the bomb using core sliding window patterns."),
    "removeduplicatesfromsortedlistii": ("Remove Duplicates from Sorted List II", "Linked List", "MEDIUM", ["Linked List"], "Practice remove duplicates from sorted list ii using core linked list patterns."),
    "deletenode": ("Delete Node", "Linked List", "EASY", ["Linked List"], "Practice delete node using core linked list patterns."),
    "diameterofbinarytree": ("Diameter Of Binary Tree", "Trees", "EASY", ["Tree", "DFS"], "Practice diameter of binary tree using core trees patterns."),
    "dietplanperformance": ("Diet Plan Performance", "Sliding Window", "EASY", ["Sliding Window", "Array"], "Practice diet plan performance using core sliding window patterns."),
    "evaluatedivision": ("Evaluate Division", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice evaluate division using core graphs patterns."),
    "evaluatereversepolishnotation": ("Evaluate Reverse Polish Notation", "Stack", "MEDIUM", ["Stack"], "Practice evaluate reverse polish notation using core stack patterns."),
    "findallanagramsinastring": ("Find All Anagrams In A String", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice find all anagrams in a string using core sliding window patterns."),
    "findfirstandlastpositionofelement": ("Find First And Last Position Of Element", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice find first and last position of element using core binary search patterns."),
    "findinmountainarray": ("Find In Mountain Array", "Binary Search", "HARD", ["Binary Search", "Array"], "Practice find in mountain array using core binary search patterns."),
    "findminimuminrotatedsortedarray": ("Find Minimum In Rotated Sorted Array", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice find minimum in rotated sorted array using core binary search patterns."),
    "findpeakelement": ("Find Peak Element", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice find peak element using core binary search patterns."),
    "findpeakelementii": ("Find Peak Element II", "Binary Search", "HARD", ["Binary Search", "Array"], "Practice find peak element ii using core binary search patterns."),
    "findpivotindex": ("Find Pivot Index", "Prefix Sum", "EASY", ["Prefix Sum", "Hash Map"], "Practice find pivot index using core prefix sum patterns."),
    "findsmallestlettergreaterthantarget": ("Find Smallest Letter Greater Than Target", "Binary Search", "EASY", ["Binary Search", "Array"], "Practice find smallest letter greater than target using core binary search patterns."),
    "findthedifference": ("Find The Difference", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice find the difference using core hash map / set patterns."),
    "findthetownjudge": ("Find The Town Judge", "Graphs", "EASY", ["Graph", "BFS"], "Practice find the town judge using core graphs patterns."),
    "firstbadversion": ("First Bad Version", "Binary Search", "EASY", ["Binary Search", "Array"], "Practice first bad version using core binary search patterns."),
    "firstmissingpositive": ("First Missing Positive", "Greedy", "HARD", ["Greedy", "Array"], "Practice first missing positive using core greedy patterns."),
    "firstuniquecharacterinastring": ("First Unique Character In A String", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice first unique character in a string using core hash map / set patterns."),
    "fruitintobaskets": ("Fruit Into Baskets", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice fruit into baskets using core sliding window patterns."),
    "generateparentheses": ("Generate Parentheses", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice generate parentheses using core backtracking patterns."),
    "groupanagrams": ("Group Anagrams", "Hash Map / Set", "MEDIUM", ["Hash Map", "Set"], "Practice group anagrams using core hash map / set patterns."),
    "grumpybookstoreowner": ("Grumpy Bookstore Owner", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice grumpy bookstore owner using core sliding window patterns."),
    "guessnumberhigherorlower": ("Guess Number Higher or Lower", "Binary Search", "EASY", ["Binary Search", "Array"], "Practice guess number higher or lower using core binary search patterns."),
    "handofstraights": ("Hand Of Straights", "Hash Map / Set", "MEDIUM", ["Hash Map", "Set", "Greedy"], "Practice hand of straights using core hash map / set patterns."),
    "happynumber": ("Happy Number", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice happy number using core hash map / set patterns."),
    "heightchecker": ("Height Checker", "Sorting", "EASY", ["Sorting", "Array"], "Practice height checker using core sorting patterns."),
    "insertinterval": ("Insert Interval", "Sorting", "MEDIUM", ["Sorting", "Array"], "Practice insert interval using core sorting patterns."),
    "intersectionoftwoarrays": ("Intersection Of Two Arrays", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice intersection of two arrays using core hash map / set patterns."),
    "intersectionoftwolinkedlists": ("Intersection of Two Linked Lists", "Linked List", "EASY", ["Linked List"], "Practice intersection of two linked lists using core linked list patterns."),
    "invertbinarytree": ("Invert Binary Tree", "Trees", "EASY", ["Tree", "DFS"], "Practice invert binary tree using core trees patterns."),
    "isgraphbipartite": ("Is Graph Bipartite", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice is graph bipartite using core graphs patterns."),
    "issubsequence": ("Is Subsequence", "Two Pointers", "EASY", ["Two Pointers", "Array"], "Practice is subsequence using core two pointers patterns."),
    "keysandrooms": ("Keys And Rooms", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice keys and rooms using core graphs patterns."),
    "kokoeatingbananas": ("Koko Eating Bananas", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice koko eating bananas using core binary search patterns."),
    "largestrectangleinhistogram": ("Largest Rectangle In Histogram", "Stack", "HARD", ["Stack"], "Practice largest rectangle in histogram using core stack patterns."),
    "leftandrightsumdifferences": ("Left And Right Sum Differences", "Prefix Sum", "EASY", ["Prefix Sum", "Hash Map"], "Practice left and right sum differences using core prefix sum patterns."),
    "lettercasepermutation": ("Letter Case Permutation", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice letter case permutation using core backtracking patterns."),
    "lettercombinationsofaphonenumber": ("Letter Combinations Of A Phone Number", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice letter combinations of a phone number using core backtracking patterns."),
    "lettertilespossibilities": ("Letter Tiles Possibilities", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice letter tiles possibilities using core backtracking patterns."),
    "linkedlistcycle": ("Linked List Cycle", "Linked List", "EASY", ["Linked List"], "Practice linked list cycle using core linked list patterns."),
    "linkedlistcycleii": ("Linked List Cycle II", "Linked List", "MEDIUM", ["Linked List"], "Practice linked list cycle ii using core linked list patterns."),
    "longestconsecutivesequence": ("Longest Consecutive Sequence", "Hash Map / Set", "MEDIUM", ["Hash Map", "Set"], "Practice longest consecutive sequence using core hash map / set patterns."),
    "longestrepeatingcharacterreplacement": ("Longest Repeating Character Replacement", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice longest repeating character replacement using core sliding window patterns."),
    "longestsubstringwithatmostkdistinctcharacters": ("Longest Substring With At Most K Distinct Characters", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice longest substring with at most k distinct characters using core sliding window patterns."),
    "longestsubstringwithoutrepeatingcharacters": ("Longest Substring Without Repeating Characters", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice longest substring without repeating characters using core sliding window patterns."),
    "lowestcommonancestorofabinarytree": ("Lowest Common Ancestor of a Binary Tree", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice lowest common ancestor of a binary tree using core trees patterns."),
    "lowestcommonancestorofabst": ("Lowest Common Ancestor Of ABST", "Trees", "MEDIUM", ["Tree", "DFS", "Binary Search"], "Practice lowest common ancestor of abst using core trees patterns."),
    "majorityelement": ("Majority Element", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice majority element using core hash map / set patterns."),
    "maxconsecutiveones": ("Max Consecutive Ones", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice max consecutive ones using core sliding window patterns."),
    "maximumaveragesubarrayi": ("Maximum Average Subarray I", "Sliding Window", "EASY", ["Sliding Window", "Array"], "Practice maximum average subarray i using core sliding window patterns."),
    "maximumdepthofbinarytree": ("Maximum Depth of Binary Tree", "Trees", "EASY", ["Tree", "DFS"], "Practice maximum depth of binary tree using core trees patterns."),
    "maximumnumberofvowelsinastring": ("Maximum Number Of Vowels In A String", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice maximum number of vowels in a string using core sliding window patterns."),
    "maximumpopulationyear": ("Maximum Population Year", "Prefix Sum", "EASY", ["Prefix Sum", "Hash Map"], "Practice maximum population year using core prefix sum patterns."),
    "maximumsizesubarraysumequalsk": ("Maximum Size Sub Array Sum Equals K", "Prefix Sum", "MEDIUM", ["Prefix Sum", "Hash Map"], "Practice maximum size sub array sum equals k using core prefix sum patterns."),
    "maximumsubarray": ("Maximum Subarray", "Arrays & Strings", "MEDIUM", ["Array", "String"], "Practice maximum subarray using core arrays & strings patterns."),
    "maximumsumsubarrayofsizek": ("Maximum Sum Subarray of Size K", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice maximum sum subarray of size k using core sliding window patterns."),
    "medianoftwosortedarrays": ("Median Of Two Sorted Arrays", "Binary Search", "HARD", ["Binary Search", "Array"], "Practice median of two sorted arrays using core binary search patterns."),
    "meetingrooms": ("Meeting Rooms", "Sorting", "MEDIUM", ["Sorting", "Array"], "Practice meeting rooms using core sorting patterns."),
    "mergeintervals": ("Merge Intervals", "Sorting", "MEDIUM", ["Sorting", "Array"], "Practice merge intervals using core sorting patterns."),
    "mergesortedarray": ("Merge Sorted Array", "Two Pointers", "EASY", ["Two Pointers", "Array"], "Practice merge sorted array using core two pointers patterns."),
    "mergetwosortedlists": ("Merge Two Sorted Lists", "Linked List", "EASY", ["Linked List"], "Practice merge two sorted lists using core linked list patterns."),
    "middleofthelinkedlist": ("Middle Of The Linked List", "Linked List", "EASY", ["Linked List"], "Practice middle of the linked list using core linked list patterns."),
    "minimumdeletionstomakecharacterfrequenciesunique": ("Minimum Deletions To Make Character Frequencies Unique", "Arrays & Strings", "MEDIUM", ["Array", "String"], "Practice minimum deletions to make character frequencies unique using core arrays & strings patterns."),
    "minimumdepthofbinarytree": ("Minimum Depth Of Binary Tree", "Trees", "EASY", ["Tree", "DFS"], "Practice minimum depth of binary tree using core trees patterns."),
    "minimumdifferencebetweenhighestandlowestofkscores": ("Minimum Difference Between Highestand Lowestof K Scores", "Sorting", "MEDIUM", ["Sorting", "Array"], "Practice minimum difference between highestand lowestof k scores using core sorting patterns."),
    "minimumgeneticmutation": ("Minimum Genetic Mutation", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice minimum genetic mutation using core graphs patterns."),
    "minimumnumberofdaystomakembouquets": ("Minimum Number Of Days To Make M Bouquets", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice minimum number of days to make m bouquets using core binary search patterns."),
    "minimumsizesubarraysum": ("Minimum Size Subarray Sum", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice minimum size subarray sum using core sliding window patterns."),
    "minimumwindowsubstring": ("Minimum Window Substring", "Sliding Window", "HARD", ["Sliding Window", "Array"], "Practice minimum window substring using core sliding window patterns."),
    "minstack": ("Min Stack", "Stack", "MEDIUM", ["Stack"], "Practice min stack using core stack patterns."),
    "missingnumber": ("Missing Number", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice missing number using core hash map / set patterns."),
    "movezeroes": ("Move Zeroes", "Two Pointers", "EASY", ["Two Pointers", "Array"], "Practice move zeroes using core two pointers patterns."),
    "nearestexitfromentranceinmaze": ("Nearest Exit From Entrance In Maze", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice nearest exit from entrance in maze using core graphs patterns."),
    "nextpermutation": ("Next Permutation", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice next permutation using core backtracking patterns."),
    "nonoverlappingintervals": ("Non-overlapping Intervals", "Greedy", "MEDIUM", ["Greedy", "Array"], "Practice non-overlapping intervals using core greedy patterns."),
    "nqueens": ("N Queens", "Backtracking", "HARD", ["Backtracking", "DFS"], "Practice n queens using core backtracking patterns."),
    "numberofislands": ("Number Of Islands", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice number of islands using core graphs patterns."),
    "openthelock": ("Open The Lock", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice open the lock using core graphs patterns."),
    "palindromelinkedlist": ("Palindrome Linked List", "Linked List", "EASY", ["Linked List"], "Practice palindrome linked list using core linked list patterns."),
    "palindromepartition": ("Palindrome Partition", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice palindrome partition using core backtracking patterns."),
    "partitionlist": ("Partition List", "Linked List", "MEDIUM", ["Linked List"], "Practice partition list using core linked list patterns."),
    "pathsum": ("Path Sum", "Trees", "EASY", ["Tree", "DFS"], "Practice path sum using core trees patterns."),
    "pathsumii": ("Path Sum II", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice path sum ii using core trees patterns."),
    "pathsumiii": ("Path Sum III", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice path sum iii using core trees patterns."),
    "peakindexinamountainarray": ("Peak Index in a Mountain Array", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice peak index in a mountain array using core binary search patterns."),
    "permutationinstring": ("Permutation In String", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice permutation in string using core sliding window patterns."),
    "permutations": ("Permutations", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice permutations using core backtracking patterns."),
    "permutationsequence": ("Permutation Sequence", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice permutation sequence using core backtracking patterns."),
    "permutationsii": ("Permutations II", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice permutations ii using core backtracking patterns."),
    "permutationstring": ("Permutation String", "Arrays & Strings", "MEDIUM", ["Array", "String"], "Practice permutation string using core arrays & strings patterns."),
    "productofarrayexceptself": ("Product of Array Except Self", "Prefix Sum", "MEDIUM", ["Prefix Sum", "Hash Map"], "Practice product of array except self using core prefix sum patterns."),
    "rangesumqueryimmutable": ("Range Sum Query - Immutable", "Prefix Sum", "EASY", ["Prefix Sum", "Hash Map"], "Practice range sum query - immutable using core prefix sum patterns."),
    "ransomnote": ("Ransom Note", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice ransom note using core hash map / set patterns."),
    "relativesortarray": ("Relative Sort Array", "Sorting", "MEDIUM", ["Sorting", "Array"], "Practice relative sort array using core sorting patterns."),
    "removeduplicatesfromsortedarray": ("Remove Duplicates From Sorted Array", "Two Pointers", "EASY", ["Two Pointers", "Array"], "Practice remove duplicates from sorted array using core two pointers patterns."),
    "removeduplicatesfromsortedlist": ("Remove Duplicates From Linked List", "Linked List", "EASY", ["Linked List"], "Practice remove duplicates from linked list using core linked list patterns."),
    "removeelement": ("Remove Element", "Two Pointers", "MEDIUM", ["Two Pointers", "Array"], "Practice remove element using core two pointers patterns."),
    "removelinkedlistelements": ("Remove Linked List Elements", "Linked List", "EASY", ["Linked List"], "Practice remove linked list elements using core linked list patterns."),
    "removemiddlenodeofalinkedlist": ("Remove Middle Node Of A Linked List", "Linked List", "MEDIUM", ["Linked List"], "Practice remove middle node of a linked list using core linked list patterns."),
    "removenthnodefromendoflist": ("Remove Nth Node From End of List", "Linked List", "MEDIUM", ["Linked List"], "Practice remove nth node from end of list using core linked list patterns."),
    "reorderlist": ("Reorder List", "Linked List", "MEDIUM", ["Linked List"], "Practice reorder list using core linked list patterns."),
    "reorderroutestomakeallpathsleadtozero": ("Reorder Routes To Make All Paths Lead To Zero", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice reorder routes to make all paths lead to zero using core graphs patterns."),
    "reorganizestring": ("Reorganize String", "Hash Map / Set", "MEDIUM", ["Hash Map", "Set"], "Practice reorganize string using core hash map / set patterns."),
    "replacesubstringwithbalancedstring": ("Replace Substring With Balanced String", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice replace substring with balanced string using core sliding window patterns."),
    "restoreipaddresses": ("Restore Ip Addresses", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice restore ip addresses using core backtracking patterns."),
    "reverselinkedlist": ("Reverse Linked List", "Linked List", "EASY", ["Linked List"], "Practice reverse linked list using core linked list patterns."),
    "reversestring": ("Reverse String", "Two Pointers", "EASY", ["Two Pointers", "Array"], "Practice reverse string using core two pointers patterns."),
    "rottingoranges": ("Rotting Oranges", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice rotting oranges using core graphs patterns."),
    "runningsumof1darray": ("Running Sum Of 1 D Array", "Prefix Sum", "EASY", ["Prefix Sum", "Hash Map"], "Practice running sum of 1 d array using core prefix sum patterns."),
    "sametree": ("Same Tree", "Trees", "EASY", ["Tree", "DFS"], "Practice same tree using core trees patterns."),
    "searchinrotatedsortedarray": ("Search in Rotated Sorted Array", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice search in rotated sorted array using core binary search patterns."),
    "searchinrotatedsortedarrayii": ("Search in Rotated Sorted Array II", "Binary Search", "MEDIUM", ["Binary Search", "Array"], "Practice search in rotated sorted array ii using core binary search patterns."),
    "searchinsertposition": ("Search Insert Position", "Binary Search", "EASY", ["Binary Search", "Array"], "Practice search insert position using core binary search patterns."),
    "serializeanddeserializebinarytree": ("Serializeand Deserialize Binary Tree", "Trees", "HARD", ["Tree", "DFS"], "Practice serializeand deserialize binary tree using core trees patterns."),
    "shortestpalindrome": ("Shortest Palindrome", "Arrays & Strings", "HARD", ["Array", "String"], "Practice shortest palindrome using core arrays & strings patterns."),
    "shortestpathinbinarymatrix": ("Shortest Path In Binary Matrix", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice shortest path in binary matrix using core graphs patterns."),
    "singlenumber": ("Single Number", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice single number using core hash map / set patterns."),
    "slidingwindowmaximum": ("Sliding Window Maximum", "Sliding Window", "HARD", ["Sliding Window", "Array"], "Practice sliding window maximum using core sliding window patterns."),
    "smalleststringfromleaf": ("Smallest String From Leaf", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice smallest string from leaf using core trees patterns."),
    "sortcharactersbyfrequency": ("Sort Characters By Frequency", "Hash Map / Set", "MEDIUM", ["Hash Map", "Set"], "Practice sort characters by frequency using core hash map / set patterns."),
    "sortcolors": ("Sort Colors", "Sorting", "MEDIUM", ["Sorting", "Array"], "Practice sort colors using core sorting patterns."),
    "splitarraylargestsum": ("Split Array Largest Sum", "Binary Search", "HARD", ["Binary Search", "Array"], "Practice split array largest sum using core binary search patterns."),
    "splitstringintomaxuniquesubstrings": ("Split String Into Max Unique Substrings", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice split string into max unique substrings using core backtracking patterns."),
    "squaresofasortedarray": ("Squares of a Sorted Array", "Two Pointers", "EASY", ["Two Pointers", "Array"], "Practice squares of a sorted array using core two pointers patterns."),
    "subarraysumequalsk": ("Subarray Sum Equals K", "Prefix Sum", "MEDIUM", ["Prefix Sum", "Hash Map"], "Practice subarray sum equals k using core prefix sum patterns."),
    "subsets": ("Subsets", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice subsets using core backtracking patterns."),
    "subsetsii": ("Subsets II", "Backtracking", "MEDIUM", ["Backtracking", "DFS"], "Practice subsets ii using core backtracking patterns."),
    "substringsofsizekwithkdistinctcharacters": ("Substrings Of Size K With K Distinct Characters", "Sliding Window", "MEDIUM", ["Sliding Window", "Array"], "Practice substrings of size k with k distinct characters using core sliding window patterns."),
    "substringwithconcatenationofallwords": ("Substring with Concatenation of All Words", "Sliding Window", "HARD", ["Sliding Window", "Array"], "Practice substring with concatenation of all words using core sliding window patterns."),
    "sumroottoleafnumbers": ("Sum Root To Leaf Numbers", "Trees", "MEDIUM", ["Tree", "DFS"], "Practice sum root to leaf numbers using core trees patterns."),
    "swapnodesinpairs": ("Swap Nodes In Pairs", "Linked List", "MEDIUM", ["Linked List"], "Practice swap nodes in pairs using core linked list patterns."),
    "symmetrictree": ("Symmetric Tree", "Trees", "EASY", ["Tree", "DFS"], "Practice symmetric tree using core trees patterns."),
    "taskscheduler": ("Task Scheduler", "Greedy", "MEDIUM", ["Greedy", "Array"], "Practice task scheduler using core greedy patterns."),
    "threesum": ("3Sum", "Two Pointers", "MEDIUM", ["Two Pointers", "Array"], "Practice 3sum using core two pointers patterns."),
    "topkfrequentelements": ("Top K Frequent Elements", "Hash Map / Set", "MEDIUM", ["Hash Map", "Set"], "Practice top k frequent elements using core hash map / set patterns."),
    "trappingrainwater": ("Trapping Rain Water", "Two Pointers", "HARD", ["Two Pointers", "Array"], "Practice trapping rain water using core two pointers patterns."),
    "twosum": ("Two Sum", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice two sum using core hash map / set patterns."),
    "twosumii": ("Two Sum II - Input Array Is Sorted", "Two Pointers", "MEDIUM", ["Two Pointers", "Array"], "Practice two sum ii - input array is sorted using core two pointers patterns."),
    "validanagram": ("Valid Anagram", "Hash Map / Set", "EASY", ["Hash Map", "Set"], "Practice valid anagram using core hash map / set patterns."),
    "validatebinarysearchtree": ("Validate Binary Search Tree", "Trees", "MEDIUM", ["Tree", "DFS", "Binary Search"], "Practice validate binary search tree using core trees patterns."),
    "validpalindrome": ("Valid Palindrome", "Two Pointers", "EASY", ["Two Pointers", "Array"], "Practice valid palindrome using core two pointers patterns."),
    "validparentheses": ("Valid Parentheses", "Stack", "MEDIUM", ["Stack"], "Practice valid parentheses using core stack patterns."),
    "validsudoku": ("Valid Sudoku", "Arrays & Strings", "MEDIUM", ["Array", "String"], "Practice valid sudoku using core arrays & strings patterns."),
    "wordladder": ("Word Ladder", "Graphs", "MEDIUM", ["Graph", "BFS"], "Practice word ladder using core graphs patterns."),
    "wordsearch": ("Word Search", "Backtracking", "HARD", ["Backtracking", "DFS"], "Practice word search using core backtracking patterns."),
}
