apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shortener
  name: api-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-shortener
  template:
    metadata:
      labels:
        app: api-shortener
    spec:
      containers:
        - name: api-shortener
          image: kevin475/url-shortener-api:v2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/shortener

            - name: SPRING_DATASOURCE_USERNAME
              value: admin

            - name: SPRING_DATASOURCE_PASSWORD
              value: admin

            - name: SPRING_DATA_REDIS_HOST
              value: redis

            - name: SPRING_DATA_REDIS_PORT
              value: "6379"

            - name: SPRING_PROFILES_ACTIVE
              value: k8s