-- Creating the bank database

CREATE STOGROUP STOG1
VOLUMES(SBSYS1)
VCAT DSNCAT;

CREATE DATABASE BANK          
STOGROUP STOG1                   
BUFFERPOOL BP0;      

CREATE TABLESPACE TSBANK
IN BANK
USING STOGROUP STOG1
PRIQTY 500
SECQTY 100
BUFFERPOOL BP0
LOCKSIZE ROW
LOCKMAX SYSTEM
CLOSE YES;

CREATE TABLE ACCOUNTS_NEW(                        
  ACCOUNT_ID INTEGER GENERATED ALWAYS AS IDENTITY,
  BALANCE DECIMAL(15,2) NOT NULL DEFAULT 0,       
  STATUS CHAR(1) DEFAULT 'A',                     
  CONSTRAINT PK_ACCOUNTS PRIMARY KEY(ACCOUNT_ID)  
  ) IN BANK.TSBANK;                               

CREATE UNIQUE INDEX IDX_ACC_NUM
ON IBMUSER.ACCOUNTS (ACCOUNT_NUMBER);

CREATE TABLE TRANSACTIONS (                                     
  TX_ID INTEGER GENERATED ALWAYS AS IDENTITY,                   
  TX_TYPE CHAR(1) NOT NULL,                                     
  AMOUNT DECIMAL(15,2) NOT NULL,                                
  SOURCE_ACCOUNT CHAR(12),                                      
  TARGET_ACOUNT CHAR(12),                                       
  CREATED_AT TIMESTAMP,                                         
  CONSTRAINT PK_TX PRIMARY KEY (TX_ID)                          
  ) IN BANK.TSBANK;                                             
 CREATE UNIQUE INDEX IDX_TX_ID ON IBMUSER.TRANSACTIONS (TX_ID); 

CREATE TABLE USERS (
    USER_ID INTEGER GENERATED ALWAYS AS IDENTITY,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    STATUS CHAR(1) DEFAULT 'A', 

    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL)
) IN BANK.TSBANK;
CREATE UNIQUE INDEX IDX_USER_ID ON IBMUSER.USERS(USER_ID);

ALTER TABLE IBMUSER.ACCOUNTS
ADD USER_ID INTEGER;

ALTER TABLE IBMUSER.ACCOUNTS
ADD CONSTRAINT FK_ACC_USER
FOREIGN KEY (USER_ID)
REFERENCES IBMUSER.USERS (USER_ID)
ON DELETE RESTRICT;

ALTER TABLE IBMUSER.TRANSACTIONS
ADD CONSTRAINT FK_TX_SOURCE
FOREIGN KEY (SOURCE_ACCOUNT)
REFERENCES IBMUSER.ACCOUNTS (ACCOUNT_NUMBER)
ON DELETE RESTRICT;

ALTER TABLE IBMUSER.TRANSACTIONS
ADD CONSTRAINT FK_TX_TARGET
FOREIGN KEY (TARGET_ACCOUNT)
REFERENCES IBMUSER.ACCOUNTS (ACCOUNT_NUMBER)
ON DELETE RESTRICT;