CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    website VARCHAR(512),
    CONSTRAINT uq_companies_name UNIQUE (name)
);

CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    company_id BIGINT NOT NULL REFERENCES companies (id),
    description TEXT,
    location VARCHAR(255),
    salary_min NUMERIC(12, 2),
    salary_max NUMERIC(12, 2),
    source VARCHAR(100) NOT NULL,
    url VARCHAR(1024) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_jobs_source_url UNIQUE (source, url)
);

CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES jobs (id),
    status VARCHAR(50) NOT NULL,
    applied_at TIMESTAMP WITH TIME ZONE,
    notes TEXT
);

CREATE TABLE search_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    keywords TEXT NOT NULL,
    filters TEXT
);
