spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/feature_flags_db
spring.datasource.username=feature_user
spring.datasource.password=feature_pass

spring.data.redis.host=localhost
spring.data.redis.port=6379
security.jwt.secret-key=5367566859703373367639792F423F452848284D6251655468576D5A71347437