version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: feature-flags-postgres
    restart: always
    environment:
      POSTGRES_DB: feature_flags_db
      POSTGRES_USER: feature_user
      POSTGRES_PASSWORD: feature_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - feature-flags-network

  redis:
    image: redis:7
    container_name: feature-flags-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - feature-flags-network

volumes:
  postgres_data:
  redis_data:

networks:
  feature-flags-network:
    driver: bridge